// Angular/src/app/components/selector/selector.component.ts
import { Component, OnInit, EventEmitter, Output, Input } from '@angular/core';
import hands, { Hand } from '@shared/helpers/hands';

@Component({
  selector: 'app-selector',
  templateUrl: './selector.component.html',
  styleUrls: ['./selector.component.scss']
})
export class SelectorComponent implements OnInit {
  options: Hand[];
  selected: Hand;

  @Input() slow: boolean;

  @Output() selection: EventEmitter<Hand> = new EventEmitter();

  constructor() { }

  ngOnInit(): void {
    this.options = Object.values(hands);
  }

  reset() {
    this.selected = null;
  }

  selectHand(hand: Hand): void {
    this.selected = hand;
    this.selection.emit(hand);
  }

  isSelected(hand) {
    return this.slow && !!this.selected && this.selected === hand;
  }

  isDisabled(hand) {
    return this.slow && !!this.selected && this.selected !== hand;
  }
}

<div class="selector">
  <app-selector-hand 
    *ngFor="let hand of options"
    [hand]="hand"
    [disabled]="isDisabled(hand)"
    [selected]="isSelected(hand)"
    (selection)="selectHand($event)">
  </app-selector-hand>
</div>

// vue-2-options/src/components/Selector.vue
<template>
	<div class="selector">
		<selector-hand 
      v-for="hand in options"
      :key="hand.name"
      :hand="hand"
      :disabled="isDisabled(hand)"
      :selected="isSelected(hand)"
      @select="selectHand" />
	</div>
</template>

<script lang="ts">
import Vue from 'vue';
import SelectorHand from './SelectorHand.vue';
import hands, { Hand } from '@shared/helpers/hands';

interface Data {
  options: Hand[];
  selected: Hand | null;
}

export default Vue.extend({
	name: 'Selector',
	components: {
		SelectorHand
	},
  props: {
    slow: {
      type: Boolean,
      default: false
    }
  },
	data(): Data {
		return {
			options: Object.values(hands),
			selected: null
		};
	},
	methods: {
		reset() {
			this.selected = null;
		},
		selectHand(hand: Hand): void {
			console.log(hand);
			this.selected = hand;
			this.$emit('select', hand);
		},
		isSelected(hand: Hand) {
			return this.slow && !!this.selected && this.selected === hand;
		},
		isDisabled(hand: Hand) {
			return this.slow && !!this.selected && this.selected !== hand;
		}
	}
});
</script>

<style lang="scss">
.selector {
	display: block;
	width: max-content;
	margin: auto;
	position: relative;
}
</style>
